<?php

return [
    [
        'location'          => '北京市朝阳区东三环中路',
        'fine_amount'       => 200,
        'penalty_points'    => 3,
        'violation_content' => '机动车违反禁止标线指示',
        'vmv_remark'        => '压实线变道，电子警察抓拍',
    ],
    [
        'location'          => '上海市徐汇区肇嘉浜路与裕德路路口',
        'fine_amount'       => 150,
        'penalty_points'    => 2,
        'violation_content' => '驾驶机动车不按规定车道行驶',
        'vmv_remark'        => '实线内临时变更车道',
    ],
    [
        'location'          => '广州市天河区体育东路',
        'fine_amount'       => 200,
        'penalty_points'    => 3,
        'violation_content' => '违反禁止标志指示',
        'vmv_remark'        => '禁左路口强行左转',
    ],
    [
        'location'          => '深圳市南山区深南大道科技园路段',
        'fine_amount'       => 300,
        'penalty_points'    => 6,
        'violation_content' => '驾驶机动车违反道路交通信号灯规定',
        'vmv_remark'        => '红灯亮起后仍闯入路口',
    ],
    [
        'location'          => '杭州市西湖区文三路与学院路交叉口',
        'fine_amount'       => 100,
        'penalty_points'    => 1,
        'violation_content' => '未按规定使用转向灯',
        'vmv_remark'        => '变道及转弯均未提前打灯',
    ],
    [
        'location'          => '南京市鼓楼区中山北路',
        'fine_amount'       => 200,
        'penalty_points'    => 3,
        'violation_content' => '在禁止停车路段停车',
        'vmv_remark'        => '长时间占用机动车道，影响通行',
    ],
    [
        'location'          => '成都市锦江区红星路四段',
        'fine_amount'       => 150,
        'penalty_points'    => 2,
        'violation_content' => '在城市快速路上倒车、逆行',
        'vmv_remark'        => '因错过出口在匝道上倒车',
    ],
    [
        'location'          => '重庆市渝中区解放碑步行街周边道路',
        'fine_amount'       => 100,
        'penalty_points'    => 1,
        'violation_content' => '未按规定系安全带',
        'vmv_remark'        => '城市道路行驶中驾驶人未系安全带',
    ],
    [
        'location'          => '武汉市武昌区中北路与东湖路交界',
        'fine_amount'       => 200,
        'penalty_points'    => 3,
        'violation_content' => '通过有行人通过的人行横道未减速或停车让行',
        'vmv_remark'        => '人行横道前未礼让行人，监控抓拍',
    ],
    [
        'location'          => '西安市雁塔区长安南路电子城段',
        'fine_amount'       => 500,
        'penalty_points'    => 6,
        'violation_content' => '驾驶机动车超速行驶',
        'vmv_remark'        => '限速60km/h，实测时速86km/h',
    ],
    [
        'location'          => '天津市和平区南京路与滨江道交口',
        'fine_amount'       => 200,
        'penalty_points'    => 3,
        'violation_content' => '驾驶机动车遇斑马线未减速行驶',
        'vmv_remark'        => '前方行人通行时车速未减',
    ],
    [
        'location'          => '沈阳市沈河区青年大街市府广场段',
        'fine_amount'       => 100,
        'penalty_points'    => 1,
        'violation_content' => '行驶过程中拨打接听手持电话',
        'vmv_remark'        => '监控记录驾驶人手持手机通话',
    ],
    [
        'location'          => '大连市中山区人民路港湾广场附近',
        'fine_amount'       => 300,
        'penalty_points'    => 3,
        'violation_content' => '在设有公交专用车道的路段占用公交车道行驶',
        'vmv_remark'        => '高峰期长距离占用公交车道',
    ],
    [
        'location'          => '青岛市市南区香港中路五四广场段',
        'fine_amount'       => 150,
        'penalty_points'    => 2,
        'violation_content' => '机动车逆向行驶',
        'vmv_remark'        => '单行线逆行50米',
    ],
    [
        'location'          => '济南市历下区经十路千佛山路口',
        'fine_amount'       => 200,
        'penalty_points'    => 3,
        'violation_content' => '机动车不按导向车道行驶',
        'vmv_remark'        => '右转车道直行通过路口',
    ],
    [
        'location'          => '合肥市庐阳区长江中路市政府段',
        'fine_amount'       => 100,
        'penalty_points'    => 0,
        'violation_content' => '未按规定粘贴、悬挂检验合格标志',
        'vmv_remark'        => '前挡风玻璃未张贴年检标',
    ],
    [
        'location'          => '苏州市工业园区星湖街与现代大道交叉口',
        'fine_amount'       => 200,
        'penalty_points'    => 2,
        'violation_content' => '机动车通过路口遇黄灯加速通过',
        'vmv_remark'        => '黄灯亮起后加速闯入路口',
    ],
    [
        'location'          => '无锡市滨湖区太湖大道',
        'fine_amount'       => 300,
        'penalty_points'    => 3,
        'violation_content' => '夜间不按规定使用远光灯',
        'vmv_remark'        => '会车时长时间使用远光灯',
    ],
    [
        'location'          => '厦门市思明区环岛路音乐广场段',
        'fine_amount'       => 200,
        'penalty_points'    => 3,
        'violation_content' => '机动车在非机动车道上行驶',
        'vmv_remark'        => '为超车驶入非机动车道',
    ],
    [
        'location'          => '福州市鼓楼区五四路省政府门前路段',
        'fine_amount'       => 150,
        'penalty_points'    => 2,
        'violation_content' => '不按规定避让执行紧急任务的警车、消防车等',
        'vmv_remark'        => '未给执行任务的救护车让行',
    ],
    [
        'location'          => '南宁市青秀区民族大道国际会展中心段',
        'fine_amount'       => 200,
        'penalty_points'    => 3,
        'violation_content' => '违反禁令标志指示掉头',
        'vmv_remark'        => '禁掉头路段违规掉头',
    ],
    [
        'location'          => '昆明市盘龙区北京路与联盟路交叉口',
        'fine_amount'       => 100,
        'penalty_points'    => 1,
        'violation_content' => '机动车未按规定使用灯光',
        'vmv_remark'        => '夜间行驶未开启前照灯',
    ],
    [
        'location'          => '拉萨市城关区北京中路布达拉宫广场段',
        'fine_amount'       => 200,
        'penalty_points'    => 3,
        'violation_content' => '机动车在人行道上行驶',
        'vmv_remark'        => '为图近便驶上人行道绕行',
    ],
    [
        'location'          => '乌鲁木齐市天山区人民路红山公园附近',
        'fine_amount'       => 300,
        'penalty_points'    => 3,
        'violation_content' => '在弯道、坡道、桥梁处违法停车',
        'vmv_remark'        => '在桥上临时停车接打电话',
    ],
    [
        'location'          => '郑州市金水区花园路农业路立交桥下',
        'fine_amount'       => 200,
        'penalty_points'    => 3,
        'violation_content' => '违反禁止掉头标线指示',
        'vmv_remark'        => '左转车道内违法掉头',
    ],
    [
        'location'          => '长沙市芙蓉区五一路黄兴路口',
        'fine_amount'       => 150,
        'penalty_points'    => 2,
        'violation_content' => '在禁止鸣喇叭区域鸣喇叭',
        'vmv_remark'        => '禁鸣路段连续鸣笛催促前车',
    ],
    [
        'location'          => '石家庄市长安区中山路与建设大街交叉口',
        'fine_amount'       => 200,
        'penalty_points'    => 3,
        'violation_content' => '机动车不按右侧通行',
        'vmv_remark'        => '占用对向车道超车',
    ],
    [
        'location'          => '呼和浩特市赛罕区大学东路内蒙古大学门口',
        'fine_amount'       => 100,
        'penalty_points'    => 1,
        'violation_content' => '学校门口路段停车上下乘客',
        'vmv_remark'        => '高峰期在校门正门口临停',
    ],
    [
        'location'          => '兰州市城关区南山路黄河风情线段',
        'fine_amount'       => 200,
        'penalty_points'    => 2,
        'violation_content' => '机动车未按规定避让行人',
        'vmv_remark'        => '景区路段人车混行未减速礼让',
    ],
    [
        'location'          => '银川市兴庆区解放西街鼓楼附近',
        'fine_amount'       => 300,
        'penalty_points'    => 6,
        'violation_content' => '驾驶人未取得机动车驾驶证驾驶机动车',
        'vmv_remark'        => '驾照记分满分暂扣期间驾驶',
    ],
    [
        'location'          => '太原市迎泽区迎泽大街柳巷路段',
        'fine_amount'       => 200,
        'penalty_points'    => 3,
        'violation_content' => '机动车随意变道影响其他车辆正常行驶',
        'vmv_remark'        => '连续变道未观察后方情况',
    ],
    [
        'location'          => '长春市朝阳区人民大街文化广场段',
        'fine_amount'       => 150,
        'penalty_points'    => 2,
        'violation_content' => '机动车未按规定在车道内行驶',
        'vmv_remark'        => '压线行驶影响相邻车道',
    ],
    [
        'location'          => '哈尔滨市南岗区中山路哈工大门前',
        'fine_amount'       => 200,
        'penalty_points'    => 3,
        'violation_content' => '机动车超载行驶',
        'vmv_remark'        => '小型客车核载5人实载7人',
    ],
    [
        'location'          => '宁波市鄞州区天一广场环城西路段',
        'fine_amount'       => 100,
        'penalty_points'    => 1,
        'violation_content' => '驾驶时向车外抛洒物品',
        'vmv_remark'        => '沿途多次从窗外抛弃垃圾',
    ],
    [
        'location'          => '温州市鹿城区人民路五马街口',
        'fine_amount'       => 200,
        'penalty_points'    => 2,
        'violation_content' => '在禁止掉头区域掉头',
        'vmv_remark'        => '中央双实线路段掉头',
    ],
    [
        'location'          => '绍兴市越城区解放大道鲁迅故里段',
        'fine_amount'       => 150,
        'penalty_points'    => 2,
        'violation_content' => '景区道路乱停车',
        'vmv_remark'        => '占用非机动车道停放20分钟',
    ],
    [
        'location'          => '珠海市香洲区情侣路海滨泳场附近',
        'fine_amount'       => 200,
        'penalty_points'    => 3,
        'violation_content' => '机动车占用应急车道行驶',
        'vmv_remark'        => '拥堵时驶入应急车道超车',
    ],
    [
        'location'          => '佛山市禅城区季华路世纪莲体育中心段',
        'fine_amount'       => 300,
        'penalty_points'    => 3,
        'violation_content' => '驾车时有妨碍安全驾驶的行为',
        'vmv_remark'        => '边驾驶边操作车载导航与手机',
    ],
    [
        'location'          => '东莞市南城区鸿福路会展中心段',
        'fine_amount'       => 200,
        'penalty_points'    => 2,
        'violation_content' => '借道右转专用车道直行',
        'vmv_remark'        => '右转专用车道直行通过路口',
    ],
    [
        'location'          => '香港特别行政区九龙弥敦道佐敦路口（模拟数据）',
        'fine_amount'       => 320,
        'penalty_points'    => 3,
        'violation_content' => '十字路口违规掉头',
        'vmv_remark'        => '弥敦道繁忙路段强行掉头',
    ],
    [
        'location'          => '澳门特别行政区友谊大马路葡京酒店段（模拟数据）',
        'fine_amount'       => 260,
        'penalty_points'    => 2,
        'violation_content' => '路口黄格线内停车等待',
        'vmv_remark'        => '在黄色网格线内排队等候通行',
    ],
];
